version_name: "unet_tfefficientnetb3_hard512+896_cedice"

checkpoint_path: "./training_checkpoints/"
results_path: "./training_work_dirs/"

accumulate_grad_batches: 1
max_epochs: 30

train_data:
    type: SegmDataset
    info_path: "./data/df_kfold.csv"
    augs_config_path: "./configs/augmentations/hard_512_896.yaml"
    batch_size: 8

val_data:
    type: SegmDataset
    info_path: "./data/df_kfold.csv"
    augs_config_path: "./configs/augmentations/val_512_896.yaml"
    batch_size: 8


model:
  type: smp
  arch: unet
  parameters:
    encoder_name: tu-tf_efficientnet_b3
    encoder_weights: "imagenet"

loss:
  - type: CrossEntropyLoss
    weight: 0.5
  - type: DiceLoss
    weight: 0.5
    parameters:
      mode: multiclass

optimizer:
  type: Adam
  parameters:
      lr: 0.0003
      weight_decay: 0.00001

metrics:
  - iou

metric_to_monitor: iou
